### ISSUE TITLE
Taxon issue request template

### ISSUE THREAD

**Issue by ryanmwhitephd** [NCSLI-MII/measurand-taxonomy#42]
Review the current taxon request template and update accordingly. The taxon issue request template can be found here:
https://github.com/NCSLI-MII/measurand-taxonomy/blob/main/.github/ISSUE_TEMPLATE/TAXON-REQUEST.yml

The current content:
- Contact details
- Process type (measure, source)
- Description of the measurand (not the specification, but a detailed description understood by the requester)
- Description to the kind of quantity the measurand is associated with.
- Special token - is the taxon representing a ratio (of the same kind of quantity) or coefficient (of two different kinds of quantities)?
- Propose a taxon name according to the specification.

**Comment by ryanmwhitephd** [comment]
Within the template, add a link to the naming rules in the specification document at the Taxon name section of the template.

**Comment by ryanmwhitephd** [comment]
Suggestions:
- Add parameters to the template. Each parameter should also reference the kind of quantity. In some cases there may an enumerated list of parameter values.
- Add example taxon to help the submitter.

**Comment by MarkKuster** [comment]
Great improvement, Ryan. The text and examples should help a lot.

The first sentence in the text under the parameters field lacks some wording.

**Comment by ryanmwhitephd** [comment]
Add further clarification of the process type in reference to the particular document the measurand may be defined for, i.e. calibration cert or instrument spec.
