### ISSUE TITLE
Add CODEOWNERS file 

### ISSUE THREAD

**Issue by ryanmwhitephd** [NCSLI-MII/measurand-taxonomy#47]
Create a CODEOWNERS file to manage repository settings, in particular, reviews from codeowners during the pull request process.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

See also issue #29

**Comment by MarkKuster** [comment]
To start with, you may add me as a code owner for taxons and for docs. I assume @SchwartzMichael  will also want to own taxons at least. @ryanmwhitephd for the Flask app if-when we get to that.

**Comment by ryanmwhitephd** [comment]
@NCSLI-MII/committer-taxonomy added to CODEOWNERS file. I'll test whether this triggers an approval by one (or more) committers.
